#name, main, version and api are required
name: ExamplePlugin
main: keopiwauyu\ExamplePlugin\MainClass
src-namespace-prefix: keopiwauyu\ExamplePlugin
version: 0.0.1
api: 4.0.0

load: POSTWORLD
author: 커피와 우유
description: Example plugin showing the new API
website: https://github.com/keopiwauyu/ExamplePlugin
commands:
  example:
    description: Example command
    usage: "/example"
    permission: exampleplugin.command.example
permissions:
  exampleplugin.command.example:
    description: "Allows the user to run the example command"
    default: true
