#name, main, version and api are required
name: ZekCau
main: Endermanbugzjfc\ZekCau\MainClass
src-namespace-prefix: Endermanbugzjfc\ZekCau
version: 0.0.1
api: 4.0.0

load: POSTWORLD
author: Endermanbugzjfc
description: Example plugin showing the new API
website: https://github.com/Endermanbugzjfc/ZekCau
commands:
  example:
    description: Example command
    usage: "/example"
    permission: zekcau.command.example
permissions:
  zekcau.command.example:
    description: "Allows the user to run the example command"
    default: true
